apiVersion: v2
type: application
name: fluentbit
description: A Helm chart which deploys fluent bit
dependencies:
  - name: fluent-bit
    alias: fluentbit
    repository: https://fluent.github.io/helm-charts
    version: 0.48.6
    condition: fluentbit.enabled
appVersion: "0.48.6"
version: 1.0.2
